//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itemmaster
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string LedgerId { get; set; }
        public string UnitId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Reorder { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
