//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliermaster
    {
        public int id { get; set; }
        public string SupplierCode { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string CSTNo { get; set; }
        public Nullable<System.DateTime> CSTDate { get; set; }
        public string TINNo { get; set; }
        public Nullable<System.DateTime> TINDate { get; set; }
        public string AreaCode { get; set; }
        public string Ph1 { get; set; }
        public string Ph2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Site { get; set; }
    }
}
