//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class shimlaEntities : DbContext
    {
        public shimlaEntities()
            : base("name=shimlaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_class> tb_class { get; set; }
        public virtual DbSet<tb_classexam> tb_classexam { get; set; }
        public virtual DbSet<tb_contact> tb_contact { get; set; }
        public virtual DbSet<tb_course> tb_course { get; set; }
        public virtual DbSet<tb_eventmaster> tb_eventmaster { get; set; }
        public virtual DbSet<tb_exam> tb_exam { get; set; }
        public virtual DbSet<tb_gamemaster> tb_gamemaster { get; set; }
        public virtual DbSet<tb_item> tb_item { get; set; }
        public virtual DbSet<tb_itemprice> tb_itemprice { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_offlinefeebankdetails> tb_offlinefeebankdetails { get; set; }
        public virtual DbSet<tb_quantity> tb_quantity { get; set; }
        public virtual DbSet<tb_sankul> tb_sankul { get; set; }
        public virtual DbSet<tb_school> tb_school { get; set; }
        public virtual DbSet<tb_schoolgamedetails> tb_schoolgamedetails { get; set; }
        public virtual DbSet<tb_schoolregisetr> tb_schoolregisetr { get; set; }
        public virtual DbSet<tb_schoolstrength> tb_schoolstrength { get; set; }
        public virtual DbSet<tb_studentdetails> tb_studentdetails { get; set; }
        public virtual DbSet<tb_subitem> tb_subitem { get; set; }
        public virtual DbSet<RegisterSchool> RegisterSchools { get; set; }
        public virtual DbSet<tb_itemorder> tb_itemorder { get; set; }
        public virtual DbSet<tb_note> tb_note { get; set; }
        public virtual DbSet<tb_schoolcourse> tb_schoolcourse { get; set; }
        public virtual DbSet<tb_soprtstudent> tb_soprtstudent { get; set; }
        public virtual DbSet<tb_studentmaster> tb_studentmaster { get; set; }
        public virtual DbSet<checking> checkings { get; set; }
        public virtual DbSet<Itemmaster> Itemmasters { get; set; }
        public virtual DbSet<LedgerMaster> LedgerMasters { get; set; }
        public virtual DbSet<Samitimaster> Samitimasters { get; set; }
        public virtual DbSet<Suppliermaster> Suppliermasters { get; set; }
        public virtual DbSet<Unitmaster> Unitmasters { get; set; }
    
        public virtual int delclass(string classcode)
        {
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delclass", classcodeParameter);
        }
    
        public virtual int delclassexamfee(string classexamcode)
        {
            var classexamcodeParameter = classexamcode != null ?
                new ObjectParameter("classexamcode", classexamcode) :
                new ObjectParameter("classexamcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delclassexamfee", classexamcodeParameter);
        }
    
        public virtual int delcourse(string coursecode)
        {
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delcourse", coursecodeParameter);
        }
    
        public virtual int delexam(string examcode)
        {
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delexam", examcodeParameter);
        }
    
        public virtual int delitem(string itemcode)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delitem", itemcodeParameter);
        }
    
        public virtual int delquantity(string subitemcode)
        {
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delquantity", subitemcodeParameter);
        }
    
        public virtual int delsankul(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delsankul", codeParameter);
        }
    
        public virtual int delschool(string schoolcode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delschool", schoolcodeParameter);
        }
    
        public virtual int delschoolstrength(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delschoolstrength", idParameter);
        }
    
        public virtual int deltblogin(string schoolcode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deltblogin", schoolcodeParameter);
        }
    
        public virtual ObjectResult<dispalldetailschool_Result> dispalldetailschool(string school, string exam)
        {
            var schoolParameter = school != null ?
                new ObjectParameter("school", school) :
                new ObjectParameter("school", typeof(string));
    
            var examParameter = exam != null ?
                new ObjectParameter("exam", exam) :
                new ObjectParameter("exam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispalldetailschool_Result>("dispalldetailschool", schoolParameter, examParameter);
        }
    
        public virtual ObjectResult<dispclass_Result> dispclass()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispclass_Result>("dispclass");
        }
    
        public virtual ObjectResult<dispclassexamfee_Result> dispclassexamfee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispclassexamfee_Result>("dispclassexamfee");
        }
    
        public virtual ObjectResult<dispcourse_Result> dispcourse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispcourse_Result>("dispcourse");
        }
    
        public virtual ObjectResult<dispexam_Result> dispexam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispexam_Result>("dispexam");
        }
    
        public virtual ObjectResult<dispitem_Result> dispitem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispitem_Result>("dispitem");
        }
    
        public virtual ObjectResult<dispnote_Result> dispnote()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispnote_Result>("dispnote");
        }
    
        public virtual ObjectResult<dispquantity_Result> dispquantity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispquantity_Result>("dispquantity");
        }
    
        public virtual ObjectResult<dispsankul_Result> dispsankul()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispsankul_Result>("dispsankul");
        }
    
        public virtual ObjectResult<dispschool_Result> dispschool()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispschool_Result>("dispschool");
        }
    
        public virtual ObjectResult<dispschooldataonregistrationpage_Result> dispschooldataonregistrationpage(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispschooldataonregistrationpage_Result>("dispschooldataonregistrationpage", codeParameter);
        }
    
        public virtual ObjectResult<dispschoolregister_Result> dispschoolregister(string schoolname, string schoolcode, string schoolwebsite, string type)
        {
            var schoolnameParameter = schoolname != null ?
                new ObjectParameter("schoolname", schoolname) :
                new ObjectParameter("schoolname", typeof(string));
    
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var schoolwebsiteParameter = schoolwebsite != null ?
                new ObjectParameter("schoolwebsite", schoolwebsite) :
                new ObjectParameter("schoolwebsite", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispschoolregister_Result>("dispschoolregister", schoolnameParameter, schoolcodeParameter, schoolwebsiteParameter, typeParameter);
        }
    
        public virtual ObjectResult<dispschoolstrength_Result> dispschoolstrength(string schoolcode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dispschoolstrength_Result>("dispschoolstrength", schoolcodeParameter);
        }
    
        public virtual ObjectResult<string> findapprovestatus(string schoolcode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("findapprovestatus", schoolcodeParameter);
        }
    
        public virtual ObjectResult<findclass_Result> findclass(string classcode)
        {
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findclass_Result>("findclass", classcodeParameter);
        }
    
        public virtual ObjectResult<findclassexamfee_Result> findclassexamfee(string classexamcode)
        {
            var classexamcodeParameter = classexamcode != null ?
                new ObjectParameter("classexamcode", classexamcode) :
                new ObjectParameter("classexamcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findclassexamfee_Result>("findclassexamfee", classexamcodeParameter);
        }
    
        public virtual ObjectResult<findcourse_Result> findcourse(string coursecode)
        {
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findcourse_Result>("findcourse", coursecodeParameter);
        }
    
        public virtual ObjectResult<findexam_Result> findexam(string examcode)
        {
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findexam_Result>("findexam", examcodeParameter);
        }
    
        public virtual ObjectResult<finditem_Result> finditem(string itemcode)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<finditem_Result>("finditem", itemcodeParameter);
        }
    
        public virtual ObjectResult<findquantity_Result> findquantity(string subitemcode)
        {
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findquantity_Result>("findquantity", subitemcodeParameter);
        }
    
        public virtual ObjectResult<findsankul_Result> findsankul(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findsankul_Result>("findsankul", codeParameter);
        }
    
        public virtual ObjectResult<findschool_Result> findschool(string schoolcode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findschool_Result>("findschool", schoolcodeParameter);
        }
    
        public virtual ObjectResult<findschoolstrength_Result> findschoolstrength(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findschoolstrength_Result>("findschoolstrength", idParameter);
        }
    
        public virtual int incrementor(Nullable<int> incr, string tabelname, string idcol)
        {
            var incrParameter = incr.HasValue ?
                new ObjectParameter("incr", incr) :
                new ObjectParameter("incr", typeof(int));
    
            var tabelnameParameter = tabelname != null ?
                new ObjectParameter("tabelname", tabelname) :
                new ObjectParameter("tabelname", typeof(string));
    
            var idcolParameter = idcol != null ?
                new ObjectParameter("idcol", idcol) :
                new ObjectParameter("idcol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("incrementor", incrParameter, tabelnameParameter, idcolParameter);
        }
    
        public virtual int insclass(string classcode, string coursecode, string classname)
        {
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            var classnameParameter = classname != null ?
                new ObjectParameter("classname", classname) :
                new ObjectParameter("classname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insclass", classcodeParameter, coursecodeParameter, classnameParameter);
        }
    
        public virtual int insclassexamfee(string classexamcode, string examcode, string classcode, Nullable<double> examfee)
        {
            var classexamcodeParameter = classexamcode != null ?
                new ObjectParameter("classexamcode", classexamcode) :
                new ObjectParameter("classexamcode", typeof(string));
    
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var examfeeParameter = examfee.HasValue ?
                new ObjectParameter("examfee", examfee) :
                new ObjectParameter("examfee", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insclassexamfee", classexamcodeParameter, examcodeParameter, classcodeParameter, examfeeParameter);
        }
    
        public virtual int inscourse(string coursecode, string coursename)
        {
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            var coursenameParameter = coursename != null ?
                new ObjectParameter("coursename", coursename) :
                new ObjectParameter("coursename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inscourse", coursecodeParameter, coursenameParameter);
        }
    
        public virtual int insexam(string examcode, string examname)
        {
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            var examnameParameter = examname != null ?
                new ObjectParameter("examname", examname) :
                new ObjectParameter("examname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insexam", examcodeParameter, examnameParameter);
        }
    
        public virtual int insitem(string itemcode, string itemname)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var itemnameParameter = itemname != null ?
                new ObjectParameter("itemname", itemname) :
                new ObjectParameter("itemname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insitem", itemcodeParameter, itemnameParameter);
        }
    
        public virtual int inslogin(string username, string userpwd, Nullable<int> userrole, string schoolcode, string approvestatus)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpwdParameter = userpwd != null ?
                new ObjectParameter("userpwd", userpwd) :
                new ObjectParameter("userpwd", typeof(string));
    
            var userroleParameter = userrole.HasValue ?
                new ObjectParameter("userrole", userrole) :
                new ObjectParameter("userrole", typeof(int));
    
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var approvestatusParameter = approvestatus != null ?
                new ObjectParameter("approvestatus", approvestatus) :
                new ObjectParameter("approvestatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inslogin", usernameParameter, userpwdParameter, userroleParameter, schoolcodeParameter, approvestatusParameter);
        }
    
        public virtual int insquantity(string itemcode, string subitemcode, Nullable<int> itemquantity)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var itemquantityParameter = itemquantity.HasValue ?
                new ObjectParameter("itemquantity", itemquantity) :
                new ObjectParameter("itemquantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insquantity", itemcodeParameter, subitemcodeParameter, itemquantityParameter);
        }
    
        public virtual int inssankul(string cod, string name)
        {
            var codParameter = cod != null ?
                new ObjectParameter("Cod", cod) :
                new ObjectParameter("Cod", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inssankul", codParameter, nameParameter);
        }
    
        public virtual int insschool(string schoolcode, string schoolname, string schooladdress, string schoolemail, string principal, string session, string sankulcode, string remark, string schoolbackround, string schoollogo, string schoolstatus, string schoolaffilated, string schoolcontact, string schoolcourses)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var schoolnameParameter = schoolname != null ?
                new ObjectParameter("schoolname", schoolname) :
                new ObjectParameter("schoolname", typeof(string));
    
            var schooladdressParameter = schooladdress != null ?
                new ObjectParameter("schooladdress", schooladdress) :
                new ObjectParameter("schooladdress", typeof(string));
    
            var schoolemailParameter = schoolemail != null ?
                new ObjectParameter("schoolemail", schoolemail) :
                new ObjectParameter("schoolemail", typeof(string));
    
            var principalParameter = principal != null ?
                new ObjectParameter("principal", principal) :
                new ObjectParameter("principal", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var sankulcodeParameter = sankulcode != null ?
                new ObjectParameter("sankulcode", sankulcode) :
                new ObjectParameter("sankulcode", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var schoolbackroundParameter = schoolbackround != null ?
                new ObjectParameter("schoolbackround", schoolbackround) :
                new ObjectParameter("schoolbackround", typeof(string));
    
            var schoollogoParameter = schoollogo != null ?
                new ObjectParameter("schoollogo", schoollogo) :
                new ObjectParameter("schoollogo", typeof(string));
    
            var schoolstatusParameter = schoolstatus != null ?
                new ObjectParameter("schoolstatus", schoolstatus) :
                new ObjectParameter("schoolstatus", typeof(string));
    
            var schoolaffilatedParameter = schoolaffilated != null ?
                new ObjectParameter("schoolaffilated", schoolaffilated) :
                new ObjectParameter("schoolaffilated", typeof(string));
    
            var schoolcontactParameter = schoolcontact != null ?
                new ObjectParameter("schoolcontact", schoolcontact) :
                new ObjectParameter("schoolcontact", typeof(string));
    
            var schoolcoursesParameter = schoolcourses != null ?
                new ObjectParameter("schoolcourses", schoolcourses) :
                new ObjectParameter("schoolcourses", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insschool", schoolcodeParameter, schoolnameParameter, schooladdressParameter, schoolemailParameter, principalParameter, sessionParameter, sankulcodeParameter, remarkParameter, schoolbackroundParameter, schoollogoParameter, schoolstatusParameter, schoolaffilatedParameter, schoolcontactParameter, schoolcoursesParameter);
        }
    
        public virtual int insschoolstrength(string schoolcode, string classcode, string strength)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var strengthParameter = strength != null ?
                new ObjectParameter("strength", strength) :
                new ObjectParameter("strength", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insschoolstrength", schoolcodeParameter, classcodeParameter, strengthParameter);
        }
    
        public virtual int instbschoolcourse(string schoolcode, string coursecode)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("instbschoolcourse", schoolcodeParameter, coursecodeParameter);
        }
    
        public virtual int logincheck1(string un, string up, ObjectParameter cod, ObjectParameter code)
        {
            var unParameter = un != null ?
                new ObjectParameter("un", un) :
                new ObjectParameter("un", typeof(string));
    
            var upParameter = up != null ?
                new ObjectParameter("up", up) :
                new ObjectParameter("up", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("logincheck1", unParameter, upParameter, cod, code);
        }
    
        public virtual ObjectResult<manage_allsports_Result> manage_allsports(string school_code, string class_code, string registration_no, string admission_no, string roll_no, string student_name, string father_name, string student_dob, string student_address, string student_gender, string type)
        {
            var school_codeParameter = school_code != null ?
                new ObjectParameter("school_code", school_code) :
                new ObjectParameter("school_code", typeof(string));
    
            var class_codeParameter = class_code != null ?
                new ObjectParameter("class_code", class_code) :
                new ObjectParameter("class_code", typeof(string));
    
            var registration_noParameter = registration_no != null ?
                new ObjectParameter("registration_no", registration_no) :
                new ObjectParameter("registration_no", typeof(string));
    
            var admission_noParameter = admission_no != null ?
                new ObjectParameter("admission_no", admission_no) :
                new ObjectParameter("admission_no", typeof(string));
    
            var roll_noParameter = roll_no != null ?
                new ObjectParameter("roll_no", roll_no) :
                new ObjectParameter("roll_no", typeof(string));
    
            var student_nameParameter = student_name != null ?
                new ObjectParameter("student_name", student_name) :
                new ObjectParameter("student_name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var student_dobParameter = student_dob != null ?
                new ObjectParameter("student_dob", student_dob) :
                new ObjectParameter("student_dob", typeof(string));
    
            var student_addressParameter = student_address != null ?
                new ObjectParameter("student_address", student_address) :
                new ObjectParameter("student_address", typeof(string));
    
            var student_genderParameter = student_gender != null ?
                new ObjectParameter("student_gender", student_gender) :
                new ObjectParameter("student_gender", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_allsports_Result>("manage_allsports", school_codeParameter, class_codeParameter, registration_noParameter, admission_noParameter, roll_noParameter, student_nameParameter, father_nameParameter, student_dobParameter, student_addressParameter, student_genderParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_Bankfeedetails_Result> manage_Bankfeedetails(string schoolcode, Nullable<System.DateTime> datetime, string bankdetails, string chequeno, Nullable<System.DateTime> date, string pic, string type)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("datetime", datetime) :
                new ObjectParameter("datetime", typeof(System.DateTime));
    
            var bankdetailsParameter = bankdetails != null ?
                new ObjectParameter("bankdetails", bankdetails) :
                new ObjectParameter("bankdetails", typeof(string));
    
            var chequenoParameter = chequeno != null ?
                new ObjectParameter("chequeno", chequeno) :
                new ObjectParameter("chequeno", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_Bankfeedetails_Result>("manage_Bankfeedetails", schoolcodeParameter, datetimeParameter, bankdetailsParameter, chequenoParameter, dateParameter, picParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_eventmaster_Result> manage_eventmaster(Nullable<int> id, string event_code, string event_name, string type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var event_codeParameter = event_code != null ?
                new ObjectParameter("event_code", event_code) :
                new ObjectParameter("event_code", typeof(string));
    
            var event_nameParameter = event_name != null ?
                new ObjectParameter("event_name", event_name) :
                new ObjectParameter("event_name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_eventmaster_Result>("manage_eventmaster", idParameter, event_codeParameter, event_nameParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_gamestudents_Result> manage_gamestudents(string school_code, string class_code, string registration_no, string admission_no, string roll_no, string student_name, string father_name, string student_dob, string student_address, string student_gender, string type)
        {
            var school_codeParameter = school_code != null ?
                new ObjectParameter("school_code", school_code) :
                new ObjectParameter("school_code", typeof(string));
    
            var class_codeParameter = class_code != null ?
                new ObjectParameter("class_code", class_code) :
                new ObjectParameter("class_code", typeof(string));
    
            var registration_noParameter = registration_no != null ?
                new ObjectParameter("registration_no", registration_no) :
                new ObjectParameter("registration_no", typeof(string));
    
            var admission_noParameter = admission_no != null ?
                new ObjectParameter("admission_no", admission_no) :
                new ObjectParameter("admission_no", typeof(string));
    
            var roll_noParameter = roll_no != null ?
                new ObjectParameter("roll_no", roll_no) :
                new ObjectParameter("roll_no", typeof(string));
    
            var student_nameParameter = student_name != null ?
                new ObjectParameter("student_name", student_name) :
                new ObjectParameter("student_name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var student_dobParameter = student_dob != null ?
                new ObjectParameter("student_dob", student_dob) :
                new ObjectParameter("student_dob", typeof(string));
    
            var student_addressParameter = student_address != null ?
                new ObjectParameter("student_address", student_address) :
                new ObjectParameter("student_address", typeof(string));
    
            var student_genderParameter = student_gender != null ?
                new ObjectParameter("student_gender", student_gender) :
                new ObjectParameter("student_gender", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_gamestudents_Result>("manage_gamestudents", school_codeParameter, class_codeParameter, registration_noParameter, admission_noParameter, roll_noParameter, student_nameParameter, father_nameParameter, student_dobParameter, student_addressParameter, student_genderParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_item_Result> manage_item(string itemcode, string itemname, string type)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var itemnameParameter = itemname != null ?
                new ObjectParameter("itemname", itemname) :
                new ObjectParameter("itemname", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_item_Result>("manage_item", itemcodeParameter, itemnameParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_itemorder_Result> manage_itemorder(string type, string ordercode, string itemcode, string subitemcode, string schoolcode, Nullable<System.DateTime> orderdate, string orderstatus, Nullable<int> orderquantity)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var ordercodeParameter = ordercode != null ?
                new ObjectParameter("ordercode", ordercode) :
                new ObjectParameter("ordercode", typeof(string));
    
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var orderdateParameter = orderdate.HasValue ?
                new ObjectParameter("orderdate", orderdate) :
                new ObjectParameter("orderdate", typeof(System.DateTime));
    
            var orderstatusParameter = orderstatus != null ?
                new ObjectParameter("orderstatus", orderstatus) :
                new ObjectParameter("orderstatus", typeof(string));
    
            var orderquantityParameter = orderquantity.HasValue ?
                new ObjectParameter("orderquantity", orderquantity) :
                new ObjectParameter("orderquantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_itemorder_Result>("manage_itemorder", typeParameter, ordercodeParameter, itemcodeParameter, subitemcodeParameter, schoolcodeParameter, orderdateParameter, orderstatusParameter, orderquantityParameter);
        }
    
        public virtual ObjectResult<manage_itemprice_Result> manage_itemprice(string type, string itemcode, string subitemcode, Nullable<int> itemprice)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var itempriceParameter = itemprice.HasValue ?
                new ObjectParameter("itemprice", itemprice) :
                new ObjectParameter("itemprice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_itemprice_Result>("manage_itemprice", typeParameter, itemcodeParameter, subitemcodeParameter, itempriceParameter);
        }
    
        public virtual ObjectResult<string> manage_quantity(string itemcode, string subitemcode, Nullable<int> itemquantity, string type)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var itemquantityParameter = itemquantity.HasValue ?
                new ObjectParameter("itemquantity", itemquantity) :
                new ObjectParameter("itemquantity", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("manage_quantity", itemcodeParameter, subitemcodeParameter, itemquantityParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_schoolgamedetails_Result> manage_schoolgamedetails(string schoolplayercode, string schoolcode, string playername, string fathername, string dob, string classcode, string admission, string distt, string gamecode, string varg, string gender, string type, string status)
        {
            var schoolplayercodeParameter = schoolplayercode != null ?
                new ObjectParameter("schoolplayercode", schoolplayercode) :
                new ObjectParameter("schoolplayercode", typeof(string));
    
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var playernameParameter = playername != null ?
                new ObjectParameter("playername", playername) :
                new ObjectParameter("playername", typeof(string));
    
            var fathernameParameter = fathername != null ?
                new ObjectParameter("fathername", fathername) :
                new ObjectParameter("fathername", typeof(string));
    
            var dobParameter = dob != null ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(string));
    
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var admissionParameter = admission != null ?
                new ObjectParameter("admission", admission) :
                new ObjectParameter("admission", typeof(string));
    
            var disttParameter = distt != null ?
                new ObjectParameter("distt", distt) :
                new ObjectParameter("distt", typeof(string));
    
            var gamecodeParameter = gamecode != null ?
                new ObjectParameter("gamecode", gamecode) :
                new ObjectParameter("gamecode", typeof(string));
    
            var vargParameter = varg != null ?
                new ObjectParameter("varg", varg) :
                new ObjectParameter("varg", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_schoolgamedetails_Result>("manage_schoolgamedetails", schoolplayercodeParameter, schoolcodeParameter, playernameParameter, fathernameParameter, dobParameter, classcodeParameter, admissionParameter, disttParameter, gamecodeParameter, vargParameter, genderParameter, typeParameter, statusParameter);
        }
    
        public virtual ObjectResult<manage_studentdetails_Result> manage_studentdetails(string student_code, string school_code, string student_name, string admission_no, string roll_no, string father_name, string address, string student_class, string dob, string student_pic, string contact_no, string gender, string type)
        {
            var student_codeParameter = student_code != null ?
                new ObjectParameter("student_code", student_code) :
                new ObjectParameter("student_code", typeof(string));
    
            var school_codeParameter = school_code != null ?
                new ObjectParameter("school_code", school_code) :
                new ObjectParameter("school_code", typeof(string));
    
            var student_nameParameter = student_name != null ?
                new ObjectParameter("student_name", student_name) :
                new ObjectParameter("student_name", typeof(string));
    
            var admission_noParameter = admission_no != null ?
                new ObjectParameter("admission_no", admission_no) :
                new ObjectParameter("admission_no", typeof(string));
    
            var roll_noParameter = roll_no != null ?
                new ObjectParameter("roll_no", roll_no) :
                new ObjectParameter("roll_no", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var student_classParameter = student_class != null ?
                new ObjectParameter("student_class", student_class) :
                new ObjectParameter("student_class", typeof(string));
    
            var dobParameter = dob != null ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(string));
    
            var student_picParameter = student_pic != null ?
                new ObjectParameter("student_pic", student_pic) :
                new ObjectParameter("student_pic", typeof(string));
    
            var contact_noParameter = contact_no != null ?
                new ObjectParameter("contact_no", contact_no) :
                new ObjectParameter("contact_no", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_studentdetails_Result>("manage_studentdetails", student_codeParameter, school_codeParameter, student_nameParameter, admission_noParameter, roll_noParameter, father_nameParameter, addressParameter, student_classParameter, dobParameter, student_picParameter, contact_noParameter, genderParameter, typeParameter);
        }
    
        public virtual ObjectResult<manage_studentmaster_Result> manage_studentmaster(string school_code, Nullable<System.DateTime> admission_date, string registration_no, string class_name, string roll_no, string admission_no, string course_name, string section_name, string name, Nullable<System.DateTime> dob, string gender, string cast, string nationality, string religion, string image, string email_id, string blood_group, string matrial_status, string adhar_card, string father_name, string mother_name, string father_occupation, string father_annualincome, string desgination, string mobile_no, string father_img, string mother_img, string father_email, string parmanent_address, string temp_address, string study_time, string qulaification, string university, string state, string passing_year, string ccpa, string type)
        {
            var school_codeParameter = school_code != null ?
                new ObjectParameter("school_code", school_code) :
                new ObjectParameter("school_code", typeof(string));
    
            var admission_dateParameter = admission_date.HasValue ?
                new ObjectParameter("admission_date", admission_date) :
                new ObjectParameter("admission_date", typeof(System.DateTime));
    
            var registration_noParameter = registration_no != null ?
                new ObjectParameter("registration_no", registration_no) :
                new ObjectParameter("registration_no", typeof(string));
    
            var class_nameParameter = class_name != null ?
                new ObjectParameter("class_name", class_name) :
                new ObjectParameter("class_name", typeof(string));
    
            var roll_noParameter = roll_no != null ?
                new ObjectParameter("roll_no", roll_no) :
                new ObjectParameter("roll_no", typeof(string));
    
            var admission_noParameter = admission_no != null ?
                new ObjectParameter("admission_no", admission_no) :
                new ObjectParameter("admission_no", typeof(string));
    
            var course_nameParameter = course_name != null ?
                new ObjectParameter("course_name", course_name) :
                new ObjectParameter("course_name", typeof(string));
    
            var section_nameParameter = section_name != null ?
                new ObjectParameter("section_name", section_name) :
                new ObjectParameter("section_name", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var castParameter = cast != null ?
                new ObjectParameter("cast", cast) :
                new ObjectParameter("cast", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("nationality", nationality) :
                new ObjectParameter("nationality", typeof(string));
    
            var religionParameter = religion != null ?
                new ObjectParameter("religion", religion) :
                new ObjectParameter("religion", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var blood_groupParameter = blood_group != null ?
                new ObjectParameter("blood_group", blood_group) :
                new ObjectParameter("blood_group", typeof(string));
    
            var matrial_statusParameter = matrial_status != null ?
                new ObjectParameter("matrial_status", matrial_status) :
                new ObjectParameter("matrial_status", typeof(string));
    
            var adhar_cardParameter = adhar_card != null ?
                new ObjectParameter("adhar_card", adhar_card) :
                new ObjectParameter("adhar_card", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var mother_nameParameter = mother_name != null ?
                new ObjectParameter("mother_name", mother_name) :
                new ObjectParameter("mother_name", typeof(string));
    
            var father_occupationParameter = father_occupation != null ?
                new ObjectParameter("father_occupation", father_occupation) :
                new ObjectParameter("father_occupation", typeof(string));
    
            var father_annualincomeParameter = father_annualincome != null ?
                new ObjectParameter("father_annualincome", father_annualincome) :
                new ObjectParameter("father_annualincome", typeof(string));
    
            var desginationParameter = desgination != null ?
                new ObjectParameter("desgination", desgination) :
                new ObjectParameter("desgination", typeof(string));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var father_imgParameter = father_img != null ?
                new ObjectParameter("father_img", father_img) :
                new ObjectParameter("father_img", typeof(string));
    
            var mother_imgParameter = mother_img != null ?
                new ObjectParameter("mother_img", mother_img) :
                new ObjectParameter("mother_img", typeof(string));
    
            var father_emailParameter = father_email != null ?
                new ObjectParameter("father_email", father_email) :
                new ObjectParameter("father_email", typeof(string));
    
            var parmanent_addressParameter = parmanent_address != null ?
                new ObjectParameter("parmanent_address", parmanent_address) :
                new ObjectParameter("parmanent_address", typeof(string));
    
            var temp_addressParameter = temp_address != null ?
                new ObjectParameter("temp_address", temp_address) :
                new ObjectParameter("temp_address", typeof(string));
    
            var study_timeParameter = study_time != null ?
                new ObjectParameter("study_time", study_time) :
                new ObjectParameter("study_time", typeof(string));
    
            var qulaificationParameter = qulaification != null ?
                new ObjectParameter("qulaification", qulaification) :
                new ObjectParameter("qulaification", typeof(string));
    
            var universityParameter = university != null ?
                new ObjectParameter("university", university) :
                new ObjectParameter("university", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var passing_yearParameter = passing_year != null ?
                new ObjectParameter("passing_year", passing_year) :
                new ObjectParameter("passing_year", typeof(string));
    
            var ccpaParameter = ccpa != null ?
                new ObjectParameter("ccpa", ccpa) :
                new ObjectParameter("ccpa", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<manage_studentmaster_Result>("manage_studentmaster", school_codeParameter, admission_dateParameter, registration_noParameter, class_nameParameter, roll_noParameter, admission_noParameter, course_nameParameter, section_nameParameter, nameParameter, dobParameter, genderParameter, castParameter, nationalityParameter, religionParameter, imageParameter, email_idParameter, blood_groupParameter, matrial_statusParameter, adhar_cardParameter, father_nameParameter, mother_nameParameter, father_occupationParameter, father_annualincomeParameter, desginationParameter, mobile_noParameter, father_imgParameter, mother_imgParameter, father_emailParameter, parmanent_addressParameter, temp_addressParameter, study_timeParameter, qulaificationParameter, universityParameter, stateParameter, passing_yearParameter, ccpaParameter, typeParameter);
        }
    
        public virtual ObjectResult<string> manage_subitem(string itemcode, string subitemcode, string subitemname, string type)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var subitemnameParameter = subitemname != null ?
                new ObjectParameter("subitemname", subitemname) :
                new ObjectParameter("subitemname", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("manage_subitem", itemcodeParameter, subitemcodeParameter, subitemnameParameter, typeParameter);
        }
    
        public virtual ObjectResult<managesubgame_Result> managesubgame(string gamecode, string gamename, string type)
        {
            var gamecodeParameter = gamecode != null ?
                new ObjectParameter("gamecode", gamecode) :
                new ObjectParameter("gamecode", typeof(string));
    
            var gamenameParameter = gamename != null ?
                new ObjectParameter("gamename", gamename) :
                new ObjectParameter("gamename", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<managesubgame_Result>("managesubgame", gamecodeParameter, gamenameParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> notification()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("notification");
        }
    
        public virtual ObjectResult<Nullable<int>> notification_schoolgamedetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("notification_schoolgamedetails");
        }
    
        public virtual ObjectResult<schoolapprovelist_Result> schoolapprovelist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<schoolapprovelist_Result>("schoolapprovelist");
        }
    
        public virtual ObjectResult<schoolbysankul_Result> schoolbysankul(string sankulcode)
        {
            var sankulcodeParameter = sankulcode != null ?
                new ObjectParameter("sankulcode", sankulcode) :
                new ObjectParameter("sankulcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<schoolbysankul_Result>("schoolbysankul", sankulcodeParameter);
        }
    
        public virtual ObjectResult<string> schoolnameonmasterpage(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("schoolnameonmasterpage", codeParameter);
        }
    
        public virtual ObjectResult<totalschooldetails_Result> totalschooldetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<totalschooldetails_Result>("totalschooldetails");
        }
    
        public virtual int updclass(string classcode, string classname)
        {
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var classnameParameter = classname != null ?
                new ObjectParameter("classname", classname) :
                new ObjectParameter("classname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updclass", classcodeParameter, classnameParameter);
        }
    
        public virtual int updclassexamfee(string classexamcode, string examcode, string classcode, Nullable<double> examfee)
        {
            var classexamcodeParameter = classexamcode != null ?
                new ObjectParameter("classexamcode", classexamcode) :
                new ObjectParameter("classexamcode", typeof(string));
    
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var examfeeParameter = examfee.HasValue ?
                new ObjectParameter("examfee", examfee) :
                new ObjectParameter("examfee", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updclassexamfee", classexamcodeParameter, examcodeParameter, classcodeParameter, examfeeParameter);
        }
    
        public virtual int updcourse(string coursecode, string coursename)
        {
            var coursecodeParameter = coursecode != null ?
                new ObjectParameter("coursecode", coursecode) :
                new ObjectParameter("coursecode", typeof(string));
    
            var coursenameParameter = coursename != null ?
                new ObjectParameter("coursename", coursename) :
                new ObjectParameter("coursename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updcourse", coursecodeParameter, coursenameParameter);
        }
    
        public virtual int updexam(string examcode, string examname)
        {
            var examcodeParameter = examcode != null ?
                new ObjectParameter("examcode", examcode) :
                new ObjectParameter("examcode", typeof(string));
    
            var examnameParameter = examname != null ?
                new ObjectParameter("examname", examname) :
                new ObjectParameter("examname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updexam", examcodeParameter, examnameParameter);
        }
    
        public virtual int upditem(string itemcode, string itemname)
        {
            var itemcodeParameter = itemcode != null ?
                new ObjectParameter("itemcode", itemcode) :
                new ObjectParameter("itemcode", typeof(string));
    
            var itemnameParameter = itemname != null ?
                new ObjectParameter("itemname", itemname) :
                new ObjectParameter("itemname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upditem", itemcodeParameter, itemnameParameter);
        }
    
        public virtual int updnote(Nullable<int> id, string notification)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var notificationParameter = notification != null ?
                new ObjectParameter("notification", notification) :
                new ObjectParameter("notification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updnote", idParameter, notificationParameter);
        }
    
        public virtual int updquantity(string subitemcode, Nullable<int> itemquantity)
        {
            var subitemcodeParameter = subitemcode != null ?
                new ObjectParameter("subitemcode", subitemcode) :
                new ObjectParameter("subitemcode", typeof(string));
    
            var itemquantityParameter = itemquantity.HasValue ?
                new ObjectParameter("itemquantity", itemquantity) :
                new ObjectParameter("itemquantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updquantity", subitemcodeParameter, itemquantityParameter);
        }
    
        public virtual int updsankul(string code, string name)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updsankul", codeParameter, nameParameter);
        }
    
        public virtual int updschool(string schoolcode, string schoolname, string schooladdress, string schoolemail, string principal, string session, string sankulcode, string remark, string schoolbackround, string schoollogo, string schoolstatus, string schoolaffilated, string schoolcontact, string schoolcourse)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var schoolnameParameter = schoolname != null ?
                new ObjectParameter("schoolname", schoolname) :
                new ObjectParameter("schoolname", typeof(string));
    
            var schooladdressParameter = schooladdress != null ?
                new ObjectParameter("schooladdress", schooladdress) :
                new ObjectParameter("schooladdress", typeof(string));
    
            var schoolemailParameter = schoolemail != null ?
                new ObjectParameter("schoolemail", schoolemail) :
                new ObjectParameter("schoolemail", typeof(string));
    
            var principalParameter = principal != null ?
                new ObjectParameter("principal", principal) :
                new ObjectParameter("principal", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var sankulcodeParameter = sankulcode != null ?
                new ObjectParameter("sankulcode", sankulcode) :
                new ObjectParameter("sankulcode", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var schoolbackroundParameter = schoolbackround != null ?
                new ObjectParameter("schoolbackround", schoolbackround) :
                new ObjectParameter("schoolbackround", typeof(string));
    
            var schoollogoParameter = schoollogo != null ?
                new ObjectParameter("schoollogo", schoollogo) :
                new ObjectParameter("schoollogo", typeof(string));
    
            var schoolstatusParameter = schoolstatus != null ?
                new ObjectParameter("schoolstatus", schoolstatus) :
                new ObjectParameter("schoolstatus", typeof(string));
    
            var schoolaffilatedParameter = schoolaffilated != null ?
                new ObjectParameter("schoolaffilated", schoolaffilated) :
                new ObjectParameter("schoolaffilated", typeof(string));
    
            var schoolcontactParameter = schoolcontact != null ?
                new ObjectParameter("schoolcontact", schoolcontact) :
                new ObjectParameter("schoolcontact", typeof(string));
    
            var schoolcourseParameter = schoolcourse != null ?
                new ObjectParameter("schoolcourse", schoolcourse) :
                new ObjectParameter("schoolcourse", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updschool", schoolcodeParameter, schoolnameParameter, schooladdressParameter, schoolemailParameter, principalParameter, sessionParameter, sankulcodeParameter, remarkParameter, schoolbackroundParameter, schoollogoParameter, schoolstatusParameter, schoolaffilatedParameter, schoolcontactParameter, schoolcourseParameter);
        }
    
        public virtual int updschoolstatus(string schoolcode, string approvestatus)
        {
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var approvestatusParameter = approvestatus != null ?
                new ObjectParameter("approvestatus", approvestatus) :
                new ObjectParameter("approvestatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updschoolstatus", schoolcodeParameter, approvestatusParameter);
        }
    
        public virtual int updschoolstrength(Nullable<int> id, string schoolcode, string classcode, Nullable<int> strength)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var schoolcodeParameter = schoolcode != null ?
                new ObjectParameter("schoolcode", schoolcode) :
                new ObjectParameter("schoolcode", typeof(string));
    
            var classcodeParameter = classcode != null ?
                new ObjectParameter("classcode", classcode) :
                new ObjectParameter("classcode", typeof(string));
    
            var strengthParameter = strength.HasValue ?
                new ObjectParameter("strength", strength) :
                new ObjectParameter("strength", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updschoolstrength", idParameter, schoolcodeParameter, classcodeParameter, strengthParameter);
        }
    }
}
