//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public Nullable<int> user_role { get; set; }
        public string school_code { get; set; }
        public string approve_status { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
