//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_offlinefeebankdetails
    {
        public int id { get; set; }
        public string school_code { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string bank_details { get; set; }
        public string cheque_no { get; set; }
        public Nullable<System.DateTime> detail_date { get; set; }
        public string pic { get; set; }
    }
}
