//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_quantity
    {
        public int id { get; set; }
        public string item_code { get; set; }
        public string subitem_code { get; set; }
        public Nullable<int> item_quantity { get; set; }
    }
}
