//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_studentdetails
    {
        public int id { get; set; }
        public string student_code { get; set; }
        public string school_code { get; set; }
        public string student_name { get; set; }
        public string admission_no { get; set; }
        public string roll_no { get; set; }
        public string father_name { get; set; }
        public string student_address { get; set; }
        public string student_class { get; set; }
        public string dob { get; set; }
        public string student_pic { get; set; }
        public string contact_no { get; set; }
        public string gender { get; set; }
    }
}
